### ISSUE TITLE
Use of --no-cache-dir

### ISSUE THREAD

**Issue by DomHudson** [sleeske/docker-multi-stage-example#1]
Hi! Thanks for the Dockerfile example. I was wondering, why do you manually remove the pip cache? Is it not easier to use the `--no-cache-dir` flag that pip provides? Or is the functionality subtly different? 

Many thanks
Dom

**Comment by sleeske** [comment]
Hi Dom!

Sorry for late reply. AFAIK there is no significant difference between those two, but `--no-cache-dir` should actually be the preferred one, as it does not rely on hardcoded path.

Thanks for pointing it out, it was a good catch. I'll update the code accordingly as soon as I can ;)
Jan 

=====================================
For anyone wondering, consider the following code:

```
FROM python:3.7-alpine3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /code
COPY ./* /code/

RUN pip install -r requirements.txt && rm -rf /root/.cache/pip
```


This works fine but if can be easily broken by adding new user:
```
FROM python:3.7-alpine3.8

ENV PYTHONUNBUFFERED 1

RUN addgroup -S django \
	&& adduser -S -G django django

USER django:django

WORKDIR /code
COPY ./* /code/

RUN pip install --user -r requirements.txt && rm -rf /root/.cache/pip
```

[Because RUN is affected by USER instruction](https://docs.docker.com/v17.09/engine/reference/builder/#user) pip cache is now not stored in `/root/.cache/pip/` but rather in `/home/django/.cache/pip`.

Obviously we can make `rm` command user-independent like so: `rm -rf ~/.cache/pip`, but why bother, since `--no-cache-dir` will handle it nicely for us.

**Comment by DomHudson** [comment]
Great thanks for the response!
